### ISSUE TITLE
You should enable github pages

### ISSUE THREAD

**Issue by garronej** [AntoninJuillard/drums-game#1]
If you go in the last tab of your project you can enable github page on the master branch.  

You app will then be available at:  https://antoninjuillard.github.io/drums-game

**Comment by AntoninJuillard** [comment]
> 

thanks, I'll do that

**Comment by garronej** [comment]
Very nice.  
It's much better to show off your work without requiring the employer to pull your repo.  
I would also suggest you update the About section 
![image](https://user-images.githubusercontent.com/6702424/153508153-a32440dc-7d7b-4598-be39-9d23f2d59a6b.png)
And add your link https://antoninjuillard.github.io/drums-game

**Comment by AntoninJuillard** [comment]
> Very nice. It's much better to show off your work without requiring the employer to pull your repo. I would also suggest you update the About section ![image](https://user-images.githubusercontent.com/6702424/153508153-a32440dc-7d7b-4598-be39-9d23f2d59a6b.png) And add your link https://antoninjuillard.github.io/drums-game

I don't know if keeping these projects on github serves any purpose as they are very basic. But you're right I'll make some good descriptions. Thanks again and have a nice evening.

**Comment by garronej** [comment]
You should keep them up! 
You submitted an application for an internship with us and, as you can see, it's the first thing I've been looking at.

**Comment by AntoninJuillard** [comment]
@garronej All right. I updated the descriptions and put on github pages what could be put. I am currently working on a portfolio to show all my work.  Thanks a lot for your help :).

**Comment by garronej** [comment]
Good for you.  👍
One more tip, you can paste image to you readme to show what your app is about like:  

![image](https://user-images.githubusercontent.com/6702424/153607432-745009cb-e4de-4e52-934d-94e11ce1d9a1.png)

**Comment by AntoninJuillard** [comment]
Ok nice! I did it on all my repositories. Thanks to you my github is much better. It makes me want to code new stuff!

**Comment by garronej** [comment]
I'm glad it motivate you to code.  

You can also create a repo https://github.com/AntoninJuillard/AntoninJuillard where the README will be displayed on your profile page https://github.com/AntoninJuillad.  

Take mine for example: https://github.com/garronej/garronej

**Comment by AntoninJuillard** [comment]
Okay, I'll look into it. It looks great on your page.  Have a nice weekend.
